### ISSUE TITLE
Where are hamburger icon settings?

### ISSUE THREAD

**Issue by glow12121** [GiovanniSalmeri/yellow-miniburger#2]
Hi, Giovanni,

I was wondering where I could find the css settings for the actual hamburger icon (the three horizontal stripes)? Is it a picture or a keyboard symbol?

**Comment by GiovanniSalmeri** [comment]
I am sorry, I forgot to answer your question! The actual hamburger icon now is hardcoded as a SVG picture in line 7 of `miniburger.html`. I will look for a better solution as soon as possible!

**Comment by glow12121** [comment]
Many thanks for the answer, Giovanni! It's only now that I've seen your message.
