### ISSUE TITLE
How to center links inside divs?

### ISSUE THREAD

**Issue by glow12121** [GiovanniSalmeri/yellow-miniburger#3]
Hi,

Is it possible to (1) maximize the width of the links' divs (if those are divs at all) and (2) center the menu links inside their divs? Like in the picture below. I couldn't find the respective css settings.

* Green: divs
* Red: centered links
* Gray: page content

![burger](https://user-images.githubusercontent.com/29035180/119434963-eea08600-bd21-11eb-806c-2caea8124beb.png)

**Comment by GiovanniSalmeri** [comment]
Sorry, I forgot to answer your question! What you are easking for should be very easy to do with [Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/), when I review this extension I could add a new style for that. Thank you!
